UPDATE `chartmaster` SET `accountname` = 'Cash TKAR1-Toko KL Arjuna 1 (ex-AR)' WHERE `chartmaster`.`accountcode` = '111111118';
UPDATE `chartmaster` SET `accountname` = 'Cash TKBB2-Toko KL Batubolong 2 (ex-B3)' WHERE `chartmaster`.`accountcode` = '111111139';
UPDATE `chartmaster` SET `accountname` = 'Cash TBBB1-Toko Blink Batubolong (ex-BB)' WHERE `chartmaster`.`accountcode` = '111111126';
UPDATE `chartmaster` SET `accountname` = 'Cash TBPK1-Toko Blink Pantai Kuta 1 (ex-BK)' WHERE `chartmaster`.`accountcode` = '111111128';
UPDATE `chartmaster` SET `accountname` = 'Cash TBLE1-Toko Blink Legian 1 (ex-BL)' WHERE `chartmaster`.`accountcode` = '111111130';
UPDATE `chartmaster` SET `accountname` = 'Cash TBRU6-Toko Blink Raya Ubud 6 (ex-BU)' WHERE `chartmaster`.`accountcode` = '111111121';
UPDATE `chartmaster` SET `accountname` = 'Cash TBPL2-Toko Blink Padang Linjong 2 (ex-CB)' WHERE `chartmaster`.`accountcode` = '111111137';
UPDATE `chartmaster` SET `accountname` = 'Cash TKPL1-Toko KL Padang Linjong 1 (ex-CK)' WHERE `chartmaster`.`accountcode` = '111111136';
UPDATE `chartmaster` SET `accountname` = 'Cash TBKA3-Toko Blink Kayu Aya 3 (ex-FB)' WHERE `chartmaster`.`accountcode` = '111111143';
UPDATE `chartmaster` SET `accountname` = 'Cash TBSE3-Toko Blink Seminyak 3 (ex-GB)' WHERE `chartmaster`.`accountcode` = '111111135';
UPDATE `chartmaster` SET `accountname` = 'Cash TKSE2-Toko KL Seminyak 2 (ex-GK)' WHERE `chartmaster`.`accountcode` = '111111134';
UPDATE `chartmaster` SET `accountname` = 'Cash TBSA3-Toko Blink Sanur 3 (ex-IB)' WHERE `chartmaster`.`accountcode` = '111111142';
UPDATE `chartmaster` SET `accountname` = 'Cash TBKA2-Toko Blink Kayu Aya 2 (ex-K2)' WHERE `chartmaster`.`accountcode` = '111111129';
UPDATE `chartmaster` SET `accountname` = 'Cash TKKA1-Toko KL Kayu Aya 1 (ex-KA)' WHERE `chartmaster`.`accountcode` = '111111115';
UPDATE `chartmaster` SET `accountname` = 'Cash TKMF2-Toko KL Monkey Forest 2 (ex-M2)' WHERE `chartmaster`.`accountcode` = '111111122';
UPDATE `chartmaster` SET `accountname` = 'Cash TBMF3-Toko Blink Monkey Forest 3 (ex-M3)' WHERE `chartmaster`.`accountcode` = '111111138';
UPDATE `chartmaster` SET `accountname` = 'Cash TKMF4-Toko KL Monkey Forest 4 (ex-MF)' WHERE `chartmaster`.`accountcode` = '111111107';
UPDATE `chartmaster` SET `accountname` = 'Cash TBMF1-Toko Blink Monkey Forest 1 (ex-MU)' WHERE `chartmaster`.`accountcode` = '111111116';
UPDATE `chartmaster` SET `accountname` = 'Cash TBKR1-Toko Blink Karna 1 (ex-NB)' WHERE `chartmaster`.`accountcode` = '111111144';
UPDATE `chartmaster` SET `accountname` = 'Cash TBOB2-Toko Blink Oberoi 2 (ex-O2)' WHERE `chartmaster`.`accountcode` = '111111125';
UPDATE `chartmaster` SET `accountname` = 'Cash TKOB1-Toko KL Oberoi 1 (ex-OB)' WHERE `chartmaster`.`accountcode` = '111111112';
UPDATE `chartmaster` SET `accountname` = 'Cash TKPA1-Toko KL Padma 1 (ex-PA)' WHERE `chartmaster`.`accountcode` = '111111114';
UPDATE `chartmaster` SET `accountname` = 'Cash TBPA2-Toko Blink Padma 2 (ex-PB)' WHERE `chartmaster`.`accountcode` = '111111120';
UPDATE `chartmaster` SET `accountname` = 'Cash TBSE4-Toko Blink Seminyak 4 (ex-PS)' WHERE `chartmaster`.`accountcode` = '111111117';
UPDATE `chartmaster` SET `accountname` = 'Cash TKRU1-Toko KL Raya Ubud 1 (ex-PU)' WHERE `chartmaster`.`accountcode` = '111111110';
UPDATE `chartmaster` SET `accountname` = 'Cash TKSA1-Toko KL Sanur 1 (ex-SA)' WHERE `chartmaster`.`accountcode` = '111111102';
UPDATE `chartmaster` SET `accountname` = 'Cash TBSA2-Toko Blink Sanur 2 (ex-SB)' WHERE `chartmaster`.`accountcode` = '111111119';
UPDATE `chartmaster` SET `accountname` = 'Cash TKSE1-Toko KL Seminyak 1 (ex-SE)' WHERE `chartmaster`.`accountcode` = '111111109';
UPDATE `chartmaster` SET `accountname` = 'Cash TBTL1-Toko Blink Tanah Lot (ex-TK)' WHERE `chartmaster`.`accountcode` = '111111132';
UPDATE `chartmaster` SET `accountname` = 'Cash TKRU2-Toko KL Raya Ubud 2 (ex-U2)' WHERE `chartmaster`.`accountcode` = '111111123';
UPDATE `chartmaster` SET `accountname` = 'Cash TBRU3-Toko Blink Raya Ubud 3 (ex-U3)' WHERE `chartmaster`.`accountcode` = '111111124';
UPDATE `chartmaster` SET `accountname` = 'Cash TKRU4-Toko KL Raya Ubud 4 (ex-U4)' WHERE `chartmaster`.`accountcode` = '111111140';
UPDATE `chartmaster` SET `accountname` = 'Cash TBRU5-Toko Blink Raya Ubud 5 (ex-U5)' WHERE `chartmaster`.`accountcode` = '111111141';


UPDATE `departments` SET `description` = 'TKAR1-Toko KL Arjuna 1 (ex-AR)' WHERE `departments`.`departmentid` = 19;
UPDATE `departments` SET `description` = 'TKBB2-Toko KL Batubolong 2 (ex-B3)' WHERE `departments`.`departmentid` = 5;
UPDATE `departments` SET `description` = 'TBBB1-Toko Blink Batubolong 1 (ex-BB)' WHERE `departments`.`departmentid` = 27;
UPDATE `departments` SET `description` = 'TBPK1-Toko Blink Pantai Kuta (ex-BK)' WHERE `departments`.`departmentid` = 29;
UPDATE `departments` SET `description` = 'TBLE1-Toko Blink Legian 1 (ex-BL)' WHERE `departments`.`departmentid` = 31;
UPDATE `departments` SET `description` = 'TBRU6-Toko Blink Raya Ubud 6 (ex-BU)' WHERE `departments`.`departmentid` = 22;
UPDATE `departments` SET `description` = 'TBPL2-Toko Blink Padang Linjong 2 (ex-CB)' WHERE `departments`.`departmentid` = 28;
UPDATE `departments` SET `description` = 'TKPL1-Toko KL Padang Linjong 1 (ex-CK)' WHERE `departments`.`departmentid` = 8;
UPDATE `departments` SET `description` = 'TBKA3-Toko Blink Kayu Aya 3 (ex-FB)' WHERE `departments`.`departmentid` = 18;
UPDATE `departments` SET `description` = 'TBSE3-Toko Blink Seminyak 3 (ex-GB)' WHERE `departments`.`departmentid` = 21;
UPDATE `departments` SET `description` = 'TKSE2-Toko KL Seminyak 2 (ex-GK)' WHERE `departments`.`departmentid` = 4;
UPDATE `departments` SET `description` = 'TBSA3-Toko Blink Sanur 3 (ex-IB)' WHERE `departments`.`departmentid` = 36;
UPDATE `departments` SET `description` = 'TBKA2-Toko Blink Kayu Aya 2 (ex-K2)' WHERE `departments`.`departmentid` = 30;
UPDATE `departments` SET `description` = 'TKKA1-Toko KL Kayu Aya 1 (ex-KA)' WHERE `departments`.`departmentid` = 16;
UPDATE `departments` SET `description` = 'KANTO-Kantor KL' WHERE `departments`.`departmentid` = 1;
UPDATE `departments` SET `description` = 'TKMF2-Toko KL Monkey Forest 2 (ex-M2)' WHERE `departments`.`departmentid` = 23;
UPDATE `departments` SET `description` = 'TBMF3-Toko Blink Monkey Forest 3 (ex-M3)' WHERE `departments`.`departmentid` = 9;
UPDATE `departments` SET `description` = 'TKMF4-Toko KL Monkey Forest 4 (ex-MF)' WHERE `departments`.`departmentid` = 13;
UPDATE `departments` SET `description` = 'TBMF1-Toko Blink Monkey Forest 1 (ex-MU)' WHERE `departments`.`departmentid` = 17;
UPDATE `departments` SET `description` = 'TBKR1-Toko Blink Karna 1 (ex-NB) ' WHERE `departments`.`departmentid` = 37;
UPDATE `departments` SET `description` = 'TBOB2-Toko Blink Oberoi 2 (ex-O2)' WHERE `departments`.`departmentid` = 26;
UPDATE `departments` SET `description` = 'TKOB1-Toko KL Oberoi 1 (ex-OB)' WHERE `departments`.`departmentid` = 14;
UPDATE `departments` SET `description` = 'TKPA1-Toko KL Padma 1 (ex-PA)' WHERE `departments`.`departmentid` = 11;
UPDATE `departments` SET `description` = 'TBPA2-Toko Blink Padma 2 (ex-PB)' WHERE `departments`.`departmentid` = 2
UPDATE `departments` SET `description` = 'TBSE4-Toko Blink Seminyak 4 (ex-PS)' WHERE `departments`.`departmentid` = 35;
UPDATE `departments` SET `description` = 'TKRU1-Toko KL Raya Ubud 1 (ex-PU)' WHERE `departments`.`departmentid` = 12;
UPDATE `departments` SET `description` = 'TKSA1-Toko KL Sanur 1 (ex-SA)' WHERE `departments`.`departmentid` = 3;
UPDATE `departments` SET `description` = 'TBSA2-Toko Blink Sanur 2 (ex-SB)' WHERE `departments`.`departmentid` = 20;
UPDATE `departments` SET `description` = 'TKSE1-Toko KL Seminyak 1 (ex-SE)' WHERE `departments`.`departmentid` = 10;
UPDATE `departments` SET `description` = 'TBTL1-Toko Blink Tanah Lot 1 (ex-TK)' WHERE `departments`.`departmentid` = 33;
UPDATE `departments` SET `description` = 'TKRU2-Toko KL Raya Ubud 2 (ex-U2)' WHERE `departments`.`departmentid` = 24;
UPDATE `departments` SET `description` = 'TBRU3-Toko Blink Raya Ubud 3 (ex-U3)' WHERE `departments`.`departmentid` = 25;
UPDATE `departments` SET `description` = 'TKRU4-Toko KL Raya Ubud 4 (ex-U4)' WHERE `departments`.`departmentid` = 6;
UPDATE `departments` SET `description` = 'TBRU5-Toko Blink Raya Ubud 5 (ex-U5)' WHERE `departments`.`departmentid` = 7;
UPDATE `departments` SET `description` = 'ZZZZZ-Unused' WHERE `departments`.`departmentid` = 34;
UPDATE `departments` SET `description` = 'TBPE1-Toko Blink Petitenget 1' WHERE `departments`.`departmentid` = 15;
UPDATE `departments` SET `description` = 'TBKJ1-Toko Blink Kajeng 1' WHERE `departments`.`departmentid` = 32;

UPDATE debtorsmaster SET name = 'Toko KL Arjuna 1 (ex-AR)' WHERE debtorno ='RETAILAR';
UPDATE debtorsmaster SET name = 'Toko KL Batubolong 2 (ex-B3)' WHERE debtorno ='RETAILB3';
UPDATE debtorsmaster SET name = 'Toko Blink Batubolong 1 (ex-BB)' WHERE debtorno ='RETAILBB';
UPDATE debtorsmaster SET name = 'Toko Blink Pantai Kuta 1 (ex-BK)' WHERE debtorno ='RETAILBK';
UPDATE debtorsmaster SET name = 'Toko Blink Legian 1 (ex-BL)' WHERE debtorno ='RETAILBL';
UPDATE debtorsmaster SET name = 'Toko Blink Raya Ubud 6 (ex-BU)' WHERE debtorno ='RETAILBU';
UPDATE debtorsmaster SET name = 'Toko Blink Padang Linjong 2 (ex-CB)' WHERE debtorno ='RETAILCB';
UPDATE debtorsmaster SET name = 'Toko KL Padang Linjong 1 (ex-CK)' WHERE debtorno ='RETAILCK';
UPDATE debtorsmaster SET name = 'Toko Blink Kayu Aya 3 (ex-FB)' WHERE debtorno ='RETAILFB';
UPDATE debtorsmaster SET name = 'Toko Blink Seminyak 3 (ex-GB)' WHERE debtorno ='RETAILGB';
UPDATE debtorsmaster SET name = 'Toko KL Seminyak 2 (ex-GK)' WHERE debtorno ='RETAILGK';
UPDATE debtorsmaster SET name = 'Toko Blink Sanur 3 (ex-IB)' WHERE debtorno ='RETAILIB';
UPDATE debtorsmaster SET name = 'Toko Blink Kayu Aya 2 (ex-K2)' WHERE debtorno ='RETAILK2';
UPDATE debtorsmaster SET name = 'Toko KL Kayu Aya 1 (ex-KA)' WHERE debtorno ='RETAILKA';
UPDATE debtorsmaster SET name = 'Toko KL Monkey Forest 2 (ex-M2)' WHERE debtorno ='RETAILM2';
UPDATE debtorsmaster SET name = 'Toko Blink Monkey Forest 3 (ex-M3)' WHERE debtorno ='RETAILM3';
UPDATE debtorsmaster SET name = 'Toko KL Monkey Forest 4 (ex-MF)' WHERE debtorno ='RETAILMF';
UPDATE debtorsmaster SET name = 'Toko Blink Monkey Forest 1 (ex-MU)' WHERE debtorno ='RETAILMU';
UPDATE debtorsmaster SET name = 'Toko Blink Karna 1 (ex-NB)' WHERE debtorno ='RETAILNB';
UPDATE debtorsmaster SET name = 'Toko Blink Oberoi 2 (ex-O2)' WHERE debtorno ='RETAILO2';
UPDATE debtorsmaster SET name = 'Toko KL Oberoi 1 (ex-OB)' WHERE debtorno ='RETAILOB';
UPDATE debtorsmaster SET name = 'Toko KL Padma 1 (ex-PA)' WHERE debtorno ='RETAILPA';
UPDATE debtorsmaster SET name = 'Toko Blink Padma 2 (ex-PB)' WHERE debtorno ='RETAILPB';
UPDATE debtorsmaster SET name = 'Toko Blink Seminyak 4 (ex-PS)' WHERE debtorno ='RETAILPS';
UPDATE debtorsmaster SET name = 'Toko KL Raya Ubud 1 (ex-PU)' WHERE debtorno ='RETAILPU';
UPDATE debtorsmaster SET name = 'Toko KL Sanur 1 (ex-SA)' WHERE debtorno ='RETAILSA';
UPDATE debtorsmaster SET name = 'Toko Blink Sanur 2 (ex-SB)' WHERE debtorno ='RETAILSB';
UPDATE debtorsmaster SET name = 'Toko KL Seminyak 1 (ex-SE)' WHERE debtorno ='RETAILSE';
UPDATE debtorsmaster SET name = 'Toko Blink Tanah Lot 1 (ex-TK)' WHERE debtorno ='RETAILTK';
UPDATE debtorsmaster SET name = 'Toko KL Raya Ubud 2 (ex-U2)' WHERE debtorno ='RETAILU2';
UPDATE debtorsmaster SET name = 'Toko Blink Raya Ubud 3 (ex-U3)' WHERE debtorno ='RETAILU3';
UPDATE debtorsmaster SET name = 'Toko KL Raya Ubud 4 (ex-U4)' WHERE debtorno ='RETAILU4';
UPDATE debtorsmaster SET name = 'Toko Blink Raya Ubud 5 (ex-U5)' WHERE debtorno ='RETAILU5';

UPDATE custbranch SET brname = 'Toko KL Batubolong 2 (ex-B3)' WHERE debtorno ='RETAILB3';
UPDATE custbranch SET brname = 'Toko Blink Batubolong 1 (ex-BB)' WHERE debtorno ='RETAILBB';
UPDATE custbranch SET brname = 'Toko Blink Pantai Kuta 1 (ex-BK)' WHERE debtorno ='RETAILBK';
UPDATE custbranch SET brname = 'Toko Blink Legian 1 (ex-BL)' WHERE debtorno ='RETAILBL';
UPDATE custbranch SET brname = 'Toko Blink Raya Ubud 6 (ex-BU)' WHERE debtorno ='RETAILBU';
UPDATE custbranch SET brname = 'Toko Blink Padang Linjong 2 (ex-CB)' WHERE debtorno ='RETAILCB';
UPDATE custbranch SET brname = 'Toko KL Padang Linjong 1 (ex-CK)' WHERE debtorno ='RETAILCK';
UPDATE custbranch SET brname = 'Toko Blink Kayu Aya 3 (ex-FB)' WHERE debtorno ='RETAILFB';
UPDATE custbranch SET brname = 'Toko Blink Seminyak 3 (ex-GB)' WHERE debtorno ='RETAILGB';
UPDATE custbranch SET brname = 'Toko KL Seminyak 2 (ex-GK)' WHERE debtorno ='RETAILGK';
UPDATE custbranch SET brname = 'Toko Blink Sanur 3 (ex-IB)' WHERE debtorno ='RETAILIB';
UPDATE custbranch SET brname = 'Toko Blink Kayu Aya 2 (ex-K2)' WHERE debtorno ='RETAILK2';
UPDATE custbranch SET brname = 'Toko KL Kayu Aya 1 (ex-KA)' WHERE debtorno ='RETAILKA';
UPDATE custbranch SET brname = 'Toko KL Monkey Forest 2 (ex-M2)' WHERE debtorno ='RETAILM2';
UPDATE custbranch SET brname = 'Toko Blink Monkey Forest 3 (ex-M3)' WHERE debtorno ='RETAILM3';
UPDATE custbranch SET brname = 'Toko KL Monkey Forest 4 (ex-MF)' WHERE debtorno ='RETAILMF';
UPDATE custbranch SET brname = 'Toko Blink Monkey Forest 1 (ex-MU)' WHERE debtorno ='RETAILMU';
UPDATE custbranch SET brname = 'Toko Blink Karna 1 (ex-NB)' WHERE debtorno ='RETAILNB';
UPDATE custbranch SET brname = 'Toko Blink Oberoi 2 (ex-O2)' WHERE debtorno ='RETAILO2';
UPDATE custbranch SET brname = 'Toko KL Oberoi 1 (ex-OB)' WHERE debtorno ='RETAILOB';
UPDATE custbranch SET brname = 'Toko KL Padma 1 (ex-PA)' WHERE debtorno ='RETAILPA';
UPDATE custbranch SET brname = 'Toko Blink Padma 2 (ex-PB)' WHERE debtorno ='RETAILPB';
UPDATE custbranch SET brname = 'Toko Blink Seminyak 4 (ex-PS)' WHERE debtorno ='RETAILPS';
UPDATE custbranch SET brname = 'Toko KL Raya Ubud 1 (ex-PU)' WHERE debtorno ='RETAILPU';
UPDATE custbranch SET brname = 'Toko KL Sanur 1 (ex-SA)' WHERE debtorno ='RETAILSA';
UPDATE custbranch SET brname = 'Toko Blink Sanur 2 (ex-SB)' WHERE debtorno ='RETAILSB';
UPDATE custbranch SET brname = 'Toko KL Seminyak 1 (ex-SE)' WHERE debtorno ='RETAILSE';
UPDATE custbranch SET brname = 'Toko Blink Tanah Lot 1 (ex-TK)' WHERE debtorno ='RETAILTK';
UPDATE custbranch SET brname = 'Toko KL Raya Ubud 2 (ex-U2)' WHERE debtorno ='RETAILU2';
UPDATE custbranch SET brname = 'Toko Blink Raya Ubud 3 (ex-U3)' WHERE debtorno ='RETAILU3';
UPDATE custbranch SET brname = 'Toko KL Raya Ubud 4 (ex-U4)' WHERE debtorno ='RETAILU4';
UPDATE custbranch SET brname = 'Toko Blink Raya Ubud 5 (ex-U5)' WHERE debtorno ='RETAILU5';

UPDATE `fixedassets` 
SET `description` = 'Sewa toko TKMF2 (M2) 15/10/2027 - 15/10/2032', 
	`longdescription` = 'Sewa toko TKMF2 (M2) 15/10/2027 - 15/10/2032' 
WHERE `fixedassets`.`assetid` = 2218;

UPDATE `fixedassets` 
SET `description` = 'Sewa Toko TBKA3 (FB) 03/12/2024 - 03/03/2032', 
	`longdescription` = 'Sewa Toko TBKA3 (FB) 03/12/2024 - 03/03/2032' 
WHERE `fixedassets`.`assetid` = 2123;

UPDATE `fixedassets` 
SET `description` = 'Sewa toko TKAR1 (AR) 16/12/2023 to 16/12/2026', 
	`longdescription` = 'Sewa toko TKAR1 (AR) 16/12/2023 to 16/12/2026' 
WHERE `fixedassets`.`assetid` = 2031;

UPDATE `fixedassets` 
SET `description` = 'Sewa toko TKRU4-TBRU5 15/11/2023 to 14/11/2028', 
	`longdescription` = 'Sewa toko TKRU4-TBRU5 (U4-U5) 15/11/2023 to 14/11/2028' 
WHERE `fixedassets`.`assetid` = 2033;

UPDATE `fixedassets` 
SET `description` = 'Sewa toko TBSE4 (PS) 16/12/2023 to 16/12/2026', 
	`longdescription` = 'Sewa toko TBSE4 (PS) 16/12/2023 to 16/12/2026' 
WHERE `fixedassets`.`assetid` = 2077;



UPDATE `fixedassets` 
SET `description` = 'Sewa toko TBPE1 21/06/2026 - 08/11/2030', 
	`longdescription` = 'Sewa toko TBPE1 21/06/2026 - 08/11/2030' 
WHERE `fixedassets`.`assetid` = 2212;

UPDATE `fixedassets` 
SET `description` = 'Sewa toko TKSE1 (SE) 11/01/2026 - 11/06/2028', 
	`longdescription` = 'Sewa toko TKSE1 (SE) 11/01/2026 - 11/06/2028' 
WHERE `fixedassets`.`assetid` = 2210;

UPDATE `fixedassets` 
SET `description` = 'Sewa Toko TBBB1 (BB) 15/11/2025 to 01/05/2028', 
	`longdescription` = 'Sewa Toko TBBB1 (BB) 15/11/2025 to 01/05/2028' 
WHERE `fixedassets`.`assetid` = 2207;

UPDATE `fixedassets` 
SET `description` = 'Sewa Toko TKSE2-TBSE3 13/05/2027 - 12/05/2029', 
	`longdescription` = 'Sewa Toko TKSE2-TBSE3 (GK-GB) 13/05/2027 - 12/05/2029' 
WHERE `fixedassets`.`assetid` = 2172;

UPDATE `fixedassets` 
SET `description` = 'Sewa toko TKMF2 (M2) 15/09/2025 - 15/10/2027', 
	`longdescription` = 'Sewa toko TKMF2 (M2) 15/09/2025 - 15/10/2027' 
WHERE `fixedassets`.`assetid` = 2161;

UPDATE `fixedassets` 
SET `description` = 'Sewa Toko TBKR1 (NB) 02/08/2025 - 02/08/2031', 
	`longdescription` = 'Sewa Toko TBKR1 (NB) 02/08/2025 - 02/08/2031' 
WHERE `fixedassets`.`assetid` = 2155;

UPDATE `fixedassets` 
SET `description` = 'Sewa Toko TKPA1 (PA) 25/11/2025 - 25/11/2029', 
	`longdescription` = 'Sewa Toko TKPA1 (PA) 25/11/2025 - 25/11/2029' 
WHERE `fixedassets`.`assetid` = 2146;

UPDATE `fixedassets` 
SET `description` = 'Sewa Toko TKOB1 (OB) 25/06/2025 - 25/06/2029', 
	`longdescription` = 'Sewa Toko TKOB1 (OB) 25/06/2025 - 25/06/2029' 
WHERE `fixedassets`.`assetid` = 2140;

UPDATE `fixedassets` 
SET `description` = 'Sewa Toko TBOB2 (O2) 25/06/2025 - 25/06/2029', 
	`longdescription` = 'Sewa Toko TBOB2 (O2) 25/06/2025 - 25/06/2029' 
WHERE `fixedassets`.`assetid` = 2139;

UPDATE `fixedassets` 
SET `description` = 'Sewa Toko TKKA1 (KA) 14/04/2025 - 13/04/2030', 
	`longdescription` = 'Sewa Toko TKKA1 (KA) 14/04/2025 - 13/04/2030' 
WHERE `fixedassets`.`assetid` = 2127;

UPDATE `fixedassets` 
SET `description` = 'Sewa toko TBMF1 (MU) 01/11/2025 - 01/11/2030', 
	`longdescription` = 'Sewa toko TBMF1 (MU) 01/11/2025 - 01/11/2030' 
WHERE `fixedassets`.`assetid` = 2119;

UPDATE `fixedassets` 
SET `description` = 'Sewa toko TBSA2 (SB) 22/10/2026 to 22/10/2030', 
	`longdescription` = 'Sewa toko TBSA2 (SB) 22/10/2026 to 22/10/2030' 
WHERE `fixedassets`.`assetid` = 2116;

UPDATE `fixedassets` 
SET `description` = 'Sewa toko TBMF3 (M3) 03/11/2024 to 03/11/2027', 
	`longdescription` = 'Sewa toko TBMF3 (M3) 03/11/2024 to 03/11/2027' 
WHERE `fixedassets`.`assetid` = 2105;

UPDATE `fixedassets` 
SET `description` = 'Sewa toko TBTL1 (TK) 01/12/2024 - 01/12/2029', 
	`longdescription` = 'Sewa toko TBTL1 (TK) 01/12/2024 - 01/12/2029' 
WHERE `fixedassets`.`assetid` = 2097;

UPDATE `fixedassets` 
SET `description` = 'Sewa toko TKMF4 (MF) 17/08/2024 - 17/10/2027', 
	`longdescription` = 'Sewa toko TKMF4 (MF) 17/08/2024 - 17/10/2027' 
WHERE `fixedassets`.`assetid` = 2094;

UPDATE `fixedassets` 
SET `description` = 'Sewa toko TKRU2-TBRU3 01/10/2024 - 01/10/2027', 
	`longdescription` = 'Sewa toko TKRU2-TBRU3 (U2-U3) 01/10/2024 - 01/10/2027' 
WHERE `fixedassets`.`assetid` = 2091;

UPDATE `fixedassets` 
SET `description` = 'Sewa toko TBSA3 (IB) 02/08/2024-02/08/2030', 
	`longdescription` = 'Sewa toko TBSA3 (IB) 02/08/2024-02/08/2030' 
WHERE `fixedassets`.`assetid` = 2090;

UPDATE `fixedassets` 
SET `description` = 'Sewa toko TBLE1 (BL) 11/05/2024 to 11/05/2026', 
	`longdescription` = 'Sewa toko TBLE1 (BL) 11/05/2024 to 11/05/2026' 
WHERE `fixedassets`.`assetid` = 2085;

UPDATE `fixedassets` 
SET `description` = 'Sewa toko TKSE2-TBSE3 12/01/2024 - 12/05/2027', 
	`longdescription` = 'Sewa toko TKSE2-TBSE3 (GK-GB) 12/01/2024 - 12/05/2027' 
WHERE `fixedassets`.`assetid` = 2066;

UPDATE `fixedassets` 
SET `description` = 'Sewa toko TBRU6 (BU) 03/02/2024 - 02/05/2029', 
	`longdescription` = 'Sewa toko TBRU6 (BU) 03/02/2024 - 02/05/2029' 
WHERE `fixedassets`.`assetid` = 2063;

UPDATE `fixedassets` 
SET `description` = 'Sewa toko TBPK1 (BK) 01/12/2023 - 20/09/2026', 
	`longdescription` = 'Sewa toko TBPK1 (BK) 01/12/2023 - 20/09/2026' 
WHERE `fixedassets`.`assetid` = 2058;

UPDATE `fixedassets` 
SET `description` = 'Sewa toko TKSA1 (SA) 01/12/2023 - 06/05/2026', 
	`longdescription` = 'Sewa toko TKSA1 (SA) 01/12/2023 - 06/05/2026' 
WHERE `fixedassets`.`assetid` = 2057;

UPDATE `fixedassets` 
SET `description` = 'Sewa toko TBPA2 (PB) 01/12/2023 - 08/09/2027', 
	`longdescription` = 'Sewa toko TBPA2 (PB) 01/12/2023 - 08/09/2027' 
WHERE `fixedassets`.`assetid` = 2056;

UPDATE `fixedassets` 
SET `description` = 'Sewa toko TBSA2 (SB) 01/12/2023 - 21/10/2026', 
	`longdescription` = 'Sewa toko TBSA2 (SB) 01/12/2023 - 21/10/2026' 
WHERE `fixedassets`.`assetid` = 2055;

UPDATE `fixedassets` 
SET `description` = 'Sewa toko TKRU1 (PU) 01/02/2024 - 31/01/2029', 
	`longdescription` = 'Sewa toko TKRU1 (PU) 01/02/2024 - 31/01/2029' 
WHERE `fixedassets`.`assetid` = 2054;


