<?php
 /***************************************************************************************************
 *
 * KL RICARD: Includes functions related to session or type of webERP used
 *
 ***************************************************************************************************/

function KLDatabaseSelection(){
	// KL RICARD Select the default database depending on the code version
	if (URLWithoutScriptNameContains(".LOCAL")){
		// the current script filename resides in the WAMPP localhost, we are on TEST code
		$DefaultDatabase = 'test_erp';
	} else {
		// the current script filename resides in the production server
		if (URLWithoutScriptNameContains("/TEST")){
			// the current script filename contains TEST, we are on TEST code
			$DefaultDatabase = 'test_erp';
		}else{
			// the current script filename does not contain TEST, we are on production code
			$DefaultDatabase = 'kl_erp';
		}
	}
	return $DefaultDatabase;	
}

function KLThemeSelection(){
	if (URLWithoutScriptNameContains(".LOCAL")){
		// the current script filename resides in the WAMPP localhost, we are on TEST code
		// loalhost development environment must go with the test DB (safest)
		$Theme = 'silverwolf'; 
	} else {
		if (URLWithoutScriptNameContains("DEVELOPMENT")){
			// we are on ptadu-development.com (development code)
			if (URLWithoutScriptNameContains("/TEST")){
				// development environment with the test DB (safe)
				$Theme = 'xenos'; 
			}else{
				// development environment with the production DB (risky)
				$Theme = 'professional'; 
			}
		} else {
			// we are on ptadu.com (production code)
			if (URLWithoutScriptNameContains("/TEST")){
				// Training staff environment: we are on production code with the test DB 
				$Theme = 'gel'; 
			}else{
				// Production environment: we are on production code with the real production DB 
				$Theme = 'aguapop'; 
			}
		}
		
	}
	return $Theme;
}

function KLwebERPScriptCalledFromTEST() {
	return (URLWithoutScriptNameContains(".LOCAL") || URLWithoutScriptNameContains("/TEST"));
}

function URLWithoutScriptNameContains($keyword) {
	// Generated by GitHub Copilot 27/01/2025
    // Get the full URL
   $url = (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] === 'on' ? "https" : "http") . "://" . $_SERVER['HTTP_HOST'] . $_SERVER['REQUEST_URI'];
     
    // Remove the script name from the URL
    $scriptName = basename($_SERVER['SCRIPT_NAME']);
    $urlWithoutScript = str_replace($scriptName, '', $url);
    
    // Check if the URL contains the keyword
    return strpos(strtoupper($urlWithoutScript), strtoupper($keyword)) !== false;
}
