<?php

define("WEBERP_ONLINE_CUSTOMER_CODE_PREFIX",    'WEB-KL-');

define("LOCATIONS_WITH_STOCK_FOR_ONLINE_SHOP", 'KANTO,TOK66,TOKSA,TOKKS,TOKBW,TOKJC,TOKUB,TOKMF,TOKSE,TOKSU,TOKPU');
define("WEBERP_DISCOUNTS_IN_OPENCART_TABLE", 'product_special');

define("OPENCART_OUTLET_CATEGORIES", '51,52,53,54,55,56,59,60');
define("WEBERP_OUTLET_CATEGORIES", '51,52,53,54,55,56,59,60');

define("WEBERP_CATEGORIES_FOR_GOOGLE_PRODUCT_FEED", '31,32,33,34,36,37,50,38,35,43,44,45,46,47,48,51,52,53,54,55,56,40,41,49,42,39');

define("GOOGLE_BRAND", 'Kapal-Laut. Your Essential Jewellery');
define("GOOGLE_GENDER", 'Female');
define("GOOGLE_AGEGROUP", 'Adult');
define("GOOGLE_CONDITION", 'New');
define("GOOGLE_OOS_STATUS", 'Available for Order');
define("GOOGLE_IDENTIFIER", 'TRUE');


/*	From webERP to OpenCart */
define("PATH_OPENCART_IMAGES", 'data/KL/part_pics/');
define("ABSOLUTE_PATH_OPENCART_IMAGES", '/home4/kurakura/public_html/kapal-laut.com/image/data/KL/part_pics/');

define("PATH_OPENCART_BASE", 'http://www.kapal-laut.com');
define("ROUTE_TO_PRODUCT", 'index.php?route=product/product&');
define("REDIRECT_RESPONSE_CODE", 301);


/* From OpenCart to webERP CUSTOMERS */

define("OPENCART_DEFAULT_CUSTOMER_HOLD_REASON", '1');
define("OPENCART_DEFAULT_CUSTOMER_PAYMENT_TERMS", 'CW');
define("OPENCART_DEFAULT_CUSTOMER_SALES_TYPE", 'RT');
define("OPENCART_DEFAULT_CUSTOMER_TYPE", '9');
define("OPENCART_DEFAULT_CUSTOMER_CREDIT_LIMIT", 0);
define("OPENCART_DEFAULT_CUSTOMER_LANGUAGE", 'en_GB.utf8');
define("OPENCART_DEFAULT_CUSTOMER_TAXREF", '');
define("OPENCART_DEFAULT_CUSTOMER_TAXGROUPID", 1);

define("OPENCART_DEFAULT_SALESMAN", '999');
define("OPENCART_DEFAULT_AREA", 'OWS');
define("OPENCART_DEFAULT_AREA_INDONESIA", 'OWB');
define("OPENCART_DEFAULT_CURRENCY", 'USD');
define("OPENCART_DEFAULT_LOCATION", 'TOKWS');


define("SHIPMENT01_OPENCART_TEXT", 'EMS'); 
define("SHIPMENT01_WEBERP_CODE", 5); 
define("SHIPMENT02_OPENCART_TEXT", 'JNE-OKE'); 
define("SHIPMENT02_WEBERP_CODE", 6); 
define("SHIPMENT03_OPENCART_TEXT", 'JNE-YES'); 
define("SHIPMENT03_WEBERP_CODE", 7); 

define("OPENCART_DEFAULT_SHIPVIA", 5); 



define("OPENCART_ONLINE_COUPON_CODE", 'VIP-ONLINE-10%');
define("OPENCART_ONLINE_ORDER_DISCOUNT_CODE", 'DISCOUNT-10%');

define("OPENCART_DEFAULT_PAYMENT_SYSTEM", 'PayPal');

define("WEBERP_GL_PAYPAL_ACCOUNT_AUD",    '111259050');
define("WEBERP_GL_PAYPAL_COMMISSION_AUD", '700211700');

define("WEBERP_GL_PAYPAL_ACCOUNT_EUR",    '111259020');
define("WEBERP_GL_PAYPAL_COMMISSION_EUR", '700211700');

define("WEBERP_GL_PAYPAL_ACCOUNT_USD",    '111259010');
define("WEBERP_GL_PAYPAL_COMMISSION_USD", '700211700');

?>