CREATE TABLE `crmactivities` (
  `activityid` int NOT NULL AUTO_INCREMENT,
  `activitytype` varchar(20) NOT NULL DEFAULT 'note',
  `subject` varchar(120) NOT NULL DEFAULT '',
  `description` text,
  `debtorno` varchar(10) DEFAULT '',
  `leadid` int DEFAULT '0',
  `oppid` int DEFAULT '0',
  `contid` int DEFAULT '0',
  `assignedto` varchar(4) DEFAULT '',
  `scheduledstart` datetime DEFAULT NULL,
  `scheduledend` datetime DEFAULT NULL,
  `durationmins` int DEFAULT '0',
  `status` varchar(20) NOT NULL DEFAULT 'planned',
  `outcome` varchar(20) DEFAULT '',
  `outcomedesc` text,
  `followupdate` date DEFAULT NULL,
  `createdat` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `createdby` varchar(20) DEFAULT '',
  `completedat` datetime DEFAULT NULL,
  PRIMARY KEY (`activityid`),
  KEY `idx_debtorno` (`debtorno`),
  KEY `idx_leadid` (`leadid`),
  KEY `idx_oppid` (`oppid`),
  KEY `idx_assignedto` (`assignedto`),
  KEY `idx_scheduled` (`scheduledstart`),
  KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
