CREATE TABLE `crmleads` (
  `leadid` int NOT NULL AUTO_INCREMENT,
  `firstname` varchar(40) NOT NULL DEFAULT '',
  `lastname` varchar(40) NOT NULL DEFAULT '',
  `company` varchar(60) DEFAULT '',
  `jobtitle` varchar(40) DEFAULT '',
  `email` varchar(80) DEFAULT '',
  `phone` varchar(20) DEFAULT '',
  `mobile` varchar(20) DEFAULT '',
  `website` varchar(120) DEFAULT '',
  `address1` varchar(40) NOT NULL DEFAULT '',
  `address2` varchar(40) NOT NULL DEFAULT '',
  `address3` varchar(40) NOT NULL DEFAULT '',
  `address4` varchar(50) NOT NULL DEFAULT '',
  `address5` varchar(20) NOT NULL DEFAULT '',
  `address6` varchar(40) NOT NULL DEFAULT '',
  `industry` varchar(60) DEFAULT '',
  `sourceid` int DEFAULT '0',
  `status` varchar(20) NOT NULL DEFAULT 'new',
  `assignedto` varchar(4) DEFAULT '',
  `estimatedvalue` decimal(12,2) DEFAULT '0.00',
  `currcode` char(3) DEFAULT '',
  `notes` text,
  `convertedto` varchar(10) DEFAULT '',
  `convertedat` datetime DEFAULT NULL,
  `createdat` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `createdby` varchar(20) DEFAULT '',
  `updatedat` datetime DEFAULT NULL,
  `updatedby` varchar(20) DEFAULT '',
  PRIMARY KEY (`leadid`),
  KEY `idx_status` (`status`),
  KEY `idx_assignedto` (`assignedto`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
