CREATE TABLE `crmopportunities` (
  `oppid` int NOT NULL AUTO_INCREMENT,
  `oppname` varchar(80) NOT NULL,
  `debtorno` varchar(10) NOT NULL DEFAULT '',
  `leadid` int NOT NULL DEFAULT '0',
  `stageid` int NOT NULL DEFAULT '1',
  `probability` decimal(5,2) NOT NULL DEFAULT '0.00',
  `amount` decimal(14,2) NOT NULL DEFAULT '0.00',
  `currcode` char(3) NOT NULL DEFAULT '',
  `expectedclose` date DEFAULT NULL,
  `assignedto` varchar(4) NOT NULL DEFAULT '',
  `description` text,
  `outcome` varchar(10) NOT NULL DEFAULT 'open',
  `lostnotes` text,
  `closedat` datetime DEFAULT NULL,
  `createdat` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `createdby` varchar(20) NOT NULL DEFAULT '',
  `updatedat` datetime DEFAULT NULL,
  `updatedby` varchar(20) NOT NULL DEFAULT '',
  PRIMARY KEY (`oppid`),
  KEY `idx_stageid` (`stageid`),
  KEY `idx_assignedto` (`assignedto`),
  KEY `idx_outcome` (`outcome`),
  KEY `idx_expectedclose` (`expectedclose`),
  KEY `idx_debtorno` (`debtorno`),
  KEY `idx_leadid` (`leadid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
