CREATE TABLE `hrperformancereviews` (
	`reviewid` INT(11) NOT NULL AUTO_INCREMENT,
	`employeeid` INT(11) NOT NULL,
	`reviewdate` DATE NOT NULL,
	`reviewperiodstart` DATE DEFAULT NULL,
	`reviewperiodend` DATE DEFAULT NULL,
	`reviewtype` ENUM('Performance','Probation','Annual','Mid-Year','Project') NOT NULL,
	`reviewerid` INT(11) DEFAULT NULL,
	`overallrating` VARCHAR(50) DEFAULT NULL,
	`overallscore` DECIMAL(5,2) DEFAULT NULL,
	`strengths` TEXT,
	`areasforimprovement` TEXT,
	`goals` TEXT,
	`developmentplan` TEXT,
	`reviewercomments` TEXT,
	`employeecomments` TEXT,
	`nextreviewdate` DATE DEFAULT NULL,
	`status` ENUM('Draft','Submitted','Completed') DEFAULT 'Draft',
	`createdby` VARCHAR(50) DEFAULT NULL,
	`createddate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`modifiedby` VARCHAR(50) DEFAULT NULL,
	`modifieddate` DATETIME DEFAULT NULL,
	PRIMARY KEY (`reviewid`),
	KEY `idx_employee` (`employeeid`),
	KEY `idx_reviewer` (`reviewerid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
