CREATE TABLE `hrsafetyincidents` (
	`incidentid` INT(11) NOT NULL AUTO_INCREMENT,
	`incidentnumber` VARCHAR(20) NOT NULL,
	`incidentdate` DATETIME NOT NULL,
	`employeeid` INT(11) DEFAULT NULL,
	`locationid` VARCHAR(5) DEFAULT NULL,
	`incidenttype` ENUM('Injury','Near Miss','Property Damage','Environmental','Other') NOT NULL,
	`severity` ENUM('Minor','Moderate','Serious','Critical','Fatal') DEFAULT NULL,
	`description` TEXT NOT NULL,
	`immediateaction` TEXT,
	`rootcause` TEXT,
	`correctiveaction` TEXT,
	`reportedby` INT(11) DEFAULT NULL,
	`reporteddate` DATE DEFAULT NULL,
	`investigatedby` INT(11) DEFAULT NULL,
	`investigationdate` DATE DEFAULT NULL,
	`status` ENUM('Reported','Under Investigation','Resolved','Closed') DEFAULT 'Reported',
	`dayslost` INT(11) DEFAULT 0,
	`createddate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (`incidentid`),
	UNIQUE KEY `incidentnumber` (`incidentnumber`),
	KEY `idx_incidentdate` (`incidentdate`),
	KEY `idx_employee` (`employeeid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
