SET FOREIGN_KEY_CHECKS=0;
  
TRUNCATE `accountgroups`;
TRUNCATE `accountsection`;
TRUNCATE `areas`;
TRUNCATE `audittrail`;
TRUNCATE `bankaccounts`;
TRUNCATE `bankaccountusers`;
TRUNCATE `banktrans`;
TRUNCATE `bom`;
TRUNCATE `buckets`;
TRUNCATE `chartdetails`;
TRUNCATE `chartmaster`;
TRUNCATE `chartmasterCV`;
TRUNCATE `chartmasterM`;
TRUNCATE `chartmasterPT`;
TRUNCATE `cogsglpostings`;
TRUNCATE `companies`;
TRUNCATE `config`;
TRUNCATE `contractbom`;
TRUNCATE `contractcharges`;
TRUNCATE `contractreqts`;
TRUNCATE `contracts`;
TRUNCATE `currencies`;
TRUNCATE `custallocns`;
TRUNCATE `custbranch`;
TRUNCATE `custcontacts`;
TRUNCATE `custitem`;
TRUNCATE `custnotes`;
TRUNCATE `debtorsmaster`;
TRUNCATE `debtortrans`;
TRUNCATE `debtortranstaxes`;
TRUNCATE `debtortype`;
TRUNCATE `debtortypenotes`;
TRUNCATE `deliverynotes`;
TRUNCATE `departments`;
TRUNCATE `discountmatrix`;
TRUNCATE `ediitemmapping`;
TRUNCATE `edimessageformat`;
TRUNCATE `edi_orders_segs`;
TRUNCATE `edi_orders_seg_groups`;
TRUNCATE `emailsettings`;
TRUNCATE `factorcompanies`;
TRUNCATE `fixedassetcategories`;
TRUNCATE `fixedassetlocations`;
TRUNCATE `fixedassets`;
TRUNCATE `fixedassettasks`;
TRUNCATE `fixedassettrans`;
TRUNCATE `freightcosts`;
TRUNCATE `geocode_param`;
TRUNCATE `glaccountusers`;
TRUNCATE `gltrans`;
TRUNCATE `grns`;
TRUNCATE `holdreasons`;
TRUNCATE `internalstockcatrole`;
TRUNCATE `kladjustrl`;
TRUNCATE `klchangeprice`;
TRUNCATE `klfreeexchanges`;
TRUNCATE `klmovetodiscount20`;
TRUNCATE `klmovetodiscount50`;
TRUNCATE `klmovetodiscount80`;
TRUNCATE `klretailcustomers`;
TRUNCATE `klrevisedemaildomains`;
TRUNCATE `labelfields`;
TRUNCATE `labels`;
TRUNCATE `lastcostrollup`;
TRUNCATE `levels`;
TRUNCATE `locations`;
TRUNCATE `locationusers`;
TRUNCATE `locstock`;
TRUNCATE `loctransfercancellations`;
TRUNCATE `loctransfers`;
TRUNCATE `mailgroupdetails`;
TRUNCATE `mailgroups`;
TRUNCATE `manufacturers`;
TRUNCATE `mrpcalendar`;
TRUNCATE `mrpdemands`;
TRUNCATE `mrpdemandtypes`;
TRUNCATE `mrpparameters`;
TRUNCATE `mrpplannedorders`;
TRUNCATE `mrprequirements`;
TRUNCATE `mrpsupplies`;
TRUNCATE `offers`;
TRUNCATE `orderdeliverydifferenceslog`;
TRUNCATE `packagingused`;
TRUNCATE `paymentmethods`;
TRUNCATE `paymentterms`;
TRUNCATE `pcashdetails`;
TRUNCATE `pcexpenses`;
TRUNCATE `pctabexpenses`;
TRUNCATE `pctabs`;
TRUNCATE `pctypetabs`;
TRUNCATE `periods`;
TRUNCATE `pickinglistdetails`;
TRUNCATE `pickinglists`;
TRUNCATE `pricematrix`;
TRUNCATE `prices`;
TRUNCATE `prodspecs`;
TRUNCATE `purchdata`;
TRUNCATE `purchorderauth`;
TRUNCATE `purchorderdetails`;
TRUNCATE `purchorders`;
TRUNCATE `qasamples`;
TRUNCATE `qatests`;
TRUNCATE `recurringsalesorders`;
TRUNCATE `recurrsalesorderdetails`;
TRUNCATE `relateditems`;
TRUNCATE `reportcolumns`;
TRUNCATE `reportfields`;
TRUNCATE `reportheaders`;
TRUNCATE `reportlets`;
TRUNCATE `reportlinks`;
TRUNCATE `reports`;
TRUNCATE `salesanalysis`;
TRUNCATE `salescat`;
TRUNCATE `salescatprod`;
TRUNCATE `salescattranslations`;
TRUNCATE `salesglpostings`;
TRUNCATE `salesman`;
TRUNCATE `salesorderdetails`;
TRUNCATE `salesorders`;
TRUNCATE `salestypes`;
TRUNCATE `sampleresults`;
TRUNCATE `scripts`;
TRUNCATE `securitygroups`;
TRUNCATE `securityroles`;
TRUNCATE `securitytokens`;
TRUNCATE `sellthroughsupport`;
TRUNCATE `shipmentcharges`;
TRUNCATE `shipments`;
TRUNCATE `shippers`;
TRUNCATE `stockcategory`;
TRUNCATE `stockcatproperties`;
TRUNCATE `stockcheckfreeze`;
TRUNCATE `stockcounts`;
TRUNCATE `stockdescriptiontranslations`;
TRUNCATE `stockitemproperties`;
TRUNCATE `stockmaster`;
TRUNCATE `stockmoves`;
TRUNCATE `stockmovestaxes`;
TRUNCATE `stockrequest`;
TRUNCATE `stockrequestitems`;
TRUNCATE `stockserialitems`;
TRUNCATE `stockserialmoves`;
TRUNCATE `suppallocs`;
TRUNCATE `suppinvstogrn`;
TRUNCATE `suppliercontacts`;
TRUNCATE `supplierdiscounts`;
TRUNCATE `suppliers`;
TRUNCATE `suppliertype`;
TRUNCATE `supptrans`;
TRUNCATE `supptranstaxes`;
TRUNCATE `systypes`;
TRUNCATE `tags`;
TRUNCATE `taxauthorities`;
TRUNCATE `taxauthrates`;
TRUNCATE `taxcategories`;
TRUNCATE `taxgroups`;
TRUNCATE `taxgrouptaxes`;
TRUNCATE `taxprovinces`;
TRUNCATE `tenderitems`;
TRUNCATE `tenders`;
TRUNCATE `tendersuppliers`;
TRUNCATE `unitsofdimension`;
TRUNCATE `unitsofmeasure`;
TRUNCATE `woitems`;
TRUNCATE `worequirements`;
TRUNCATE `workcentres`;
TRUNCATE `workorders`;
TRUNCATE `woserialnos`;
TRUNCATE `www_users`;
TRUNCATE `www_users_webshop`;

  
INSERT INTO kurakura_kl_test_erp.accountgroups SELECT * FROM kurakura_kl_erp.accountgroups;
INSERT INTO kurakura_kl_test_erp.accountsection SELECT * FROM kurakura_kl_erp.accountsection;
INSERT INTO kurakura_kl_test_erp.areas SELECT * FROM kurakura_kl_erp.areas;
/* INSERT INTO kurakura_kl_test_erp.audittrail SELECT * FROM kurakura_kl_erp.audittrail; */
INSERT INTO kurakura_kl_test_erp.bankaccounts SELECT * FROM kurakura_kl_erp.bankaccounts;
INSERT INTO kurakura_kl_test_erp.bankaccountusers SELECT * FROM kurakura_kl_erp.bankaccountusers;
INSERT INTO kurakura_kl_test_erp.banktrans SELECT * FROM kurakura_kl_erp.banktrans;
INSERT INTO kurakura_kl_test_erp.bom SELECT * FROM kurakura_kl_erp.bom;
INSERT INTO kurakura_kl_test_erp.buckets SELECT * FROM kurakura_kl_erp.buckets;
INSERT INTO kurakura_kl_test_erp.chartdetails SELECT * FROM kurakura_kl_erp.chartdetails;
INSERT INTO kurakura_kl_test_erp.chartmaster SELECT * FROM kurakura_kl_erp.chartmaster;
INSERT INTO kurakura_kl_test_erp.chartmasterCV SELECT * FROM kurakura_kl_erp.chartmasterCV;
INSERT INTO kurakura_kl_test_erp.chartmasterM SELECT * FROM kurakura_kl_erp.chartmasterM;
INSERT INTO kurakura_kl_test_erp.chartmasterPT SELECT * FROM kurakura_kl_erp.chartmasterPT;
INSERT INTO kurakura_kl_test_erp.cogsglpostings SELECT * FROM kurakura_kl_erp.cogsglpostings;
INSERT INTO kurakura_kl_test_erp.companies SELECT * FROM kurakura_kl_erp.companies;
INSERT INTO kurakura_kl_test_erp.config SELECT * FROM kurakura_kl_erp.config;
INSERT INTO kurakura_kl_test_erp.contractbom SELECT * FROM kurakura_kl_erp.contractbom;
INSERT INTO kurakura_kl_test_erp.contractcharges SELECT * FROM kurakura_kl_erp.contractcharges;
INSERT INTO kurakura_kl_test_erp.contractreqts SELECT * FROM kurakura_kl_erp.contractreqts;
INSERT INTO kurakura_kl_test_erp.contracts SELECT * FROM kurakura_kl_erp.contracts;
INSERT INTO kurakura_kl_test_erp.currencies SELECT * FROM kurakura_kl_erp.currencies;
INSERT INTO kurakura_kl_test_erp.custallocns SELECT * FROM kurakura_kl_erp.custallocns;
INSERT INTO kurakura_kl_test_erp.custbranch SELECT * FROM kurakura_kl_erp.custbranch;
INSERT INTO kurakura_kl_test_erp.custcontacts SELECT * FROM kurakura_kl_erp.custcontacts;
INSERT INTO kurakura_kl_test_erp.custitem SELECT * FROM kurakura_kl_erp.custitem;
INSERT INTO kurakura_kl_test_erp.custnotes SELECT * FROM kurakura_kl_erp.custnotes;
INSERT INTO kurakura_kl_test_erp.debtorsmaster SELECT * FROM kurakura_kl_erp.debtorsmaster;
INSERT INTO kurakura_kl_test_erp.debtortrans SELECT * FROM kurakura_kl_erp.debtortrans;
INSERT INTO kurakura_kl_test_erp.debtortranstaxes SELECT * FROM kurakura_kl_erp.debtortranstaxes;
INSERT INTO kurakura_kl_test_erp.debtortype SELECT * FROM kurakura_kl_erp.debtortype;
INSERT INTO kurakura_kl_test_erp.debtortypenotes SELECT * FROM kurakura_kl_erp.debtortypenotes;
INSERT INTO kurakura_kl_test_erp.deliverynotes SELECT * FROM kurakura_kl_erp.deliverynotes;
INSERT INTO kurakura_kl_test_erp.departments SELECT * FROM kurakura_kl_erp.departments;
INSERT INTO kurakura_kl_test_erp.discountmatrix SELECT * FROM kurakura_kl_erp.discountmatrix;
INSERT INTO kurakura_kl_test_erp.edi_orders_seg_groups SELECT * FROM kurakura_kl_erp.edi_orders_seg_groups;
INSERT INTO kurakura_kl_test_erp.edi_orders_segs SELECT * FROM kurakura_kl_erp.edi_orders_segs;
INSERT INTO kurakura_kl_test_erp.ediitemmapping SELECT * FROM kurakura_kl_erp.ediitemmapping;
INSERT INTO kurakura_kl_test_erp.edimessageformat SELECT * FROM kurakura_kl_erp.edimessageformat;
INSERT INTO kurakura_kl_test_erp.emailsettings SELECT * FROM kurakura_kl_erp.emailsettings;
INSERT INTO kurakura_kl_test_erp.factorcompanies SELECT * FROM kurakura_kl_erp.factorcompanies;
INSERT INTO kurakura_kl_test_erp.fixedassetcategories SELECT * FROM kurakura_kl_erp.fixedassetcategories;
INSERT INTO kurakura_kl_test_erp.fixedassetlocations SELECT * FROM kurakura_kl_erp.fixedassetlocations;
INSERT INTO kurakura_kl_test_erp.fixedassets SELECT * FROM kurakura_kl_erp.fixedassets;
INSERT INTO kurakura_kl_test_erp.fixedassettasks SELECT * FROM kurakura_kl_erp.fixedassettasks;
INSERT INTO kurakura_kl_test_erp.fixedassettrans SELECT * FROM kurakura_kl_erp.fixedassettrans;
INSERT INTO kurakura_kl_test_erp.freightcosts SELECT * FROM kurakura_kl_erp.freightcosts;
INSERT INTO kurakura_kl_test_erp.geocode_param SELECT * FROM kurakura_kl_erp.geocode_param;
INSERT INTO kurakura_kl_test_erp.glaccountusers SELECT * FROM kurakura_kl_erp.glaccountusers;
INSERT INTO kurakura_kl_test_erp.gltrans SELECT * FROM kurakura_kl_erp.gltrans WHERE trandate > "20150101";
INSERT INTO kurakura_kl_test_erp.grns SELECT * FROM kurakura_kl_erp.grns;
INSERT INTO kurakura_kl_test_erp.holdreasons SELECT * FROM kurakura_kl_erp.holdreasons;
INSERT INTO kurakura_kl_test_erp.internalstockcatrole SELECT * FROM kurakura_kl_erp.internalstockcatrole;
INSERT INTO kurakura_kl_test_erp.kladjustrl SELECT * FROM kurakura_kl_erp.kladjustrl;
INSERT INTO kurakura_kl_test_erp.klchangeprice SELECT * FROM kurakura_kl_erp.klchangeprice;
INSERT INTO kurakura_kl_test_erp.klfreeexchanges SELECT * FROM kurakura_kl_erp.klfreeexchanges;
INSERT INTO kurakura_kl_test_erp.klmovetodiscount20 SELECT * FROM kurakura_kl_erp.klmovetodiscount20;
INSERT INTO kurakura_kl_test_erp.klmovetodiscount50 SELECT * FROM kurakura_kl_erp.klmovetodiscount50;
INSERT INTO kurakura_kl_test_erp.klmovetodiscount80 SELECT * FROM kurakura_kl_erp.klmovetodiscount80;
INSERT INTO kurakura_kl_test_erp.klretailcustomers SELECT * FROM kurakura_kl_erp.klretailcustomers;
INSERT INTO kurakura_kl_test_erp.klrevisedemaildomains SELECT * FROM kurakura_kl_erp.klrevisedemaildomains;
INSERT INTO kurakura_kl_test_erp.labelfields SELECT * FROM kurakura_kl_erp.labelfields;
INSERT INTO kurakura_kl_test_erp.labels SELECT * FROM kurakura_kl_erp.labels;
INSERT INTO kurakura_kl_test_erp.lastcostrollup SELECT * FROM kurakura_kl_erp.lastcostrollup;
INSERT INTO kurakura_kl_test_erp.levels SELECT * FROM kurakura_kl_erp.levels;
INSERT INTO kurakura_kl_test_erp.locations SELECT * FROM kurakura_kl_erp.locations;
INSERT INTO kurakura_kl_test_erp.locationusers SELECT * FROM kurakura_kl_erp.locationusers;
INSERT INTO kurakura_kl_test_erp.locstock SELECT * FROM kurakura_kl_erp.locstock;
INSERT INTO kurakura_kl_test_erp.loctransfercancellations SELECT * FROM kurakura_kl_erp.loctransfercancellations;
INSERT INTO kurakura_kl_test_erp.loctransfers SELECT * FROM kurakura_kl_erp.loctransfers;
INSERT INTO kurakura_kl_test_erp.mailgroupdetails SELECT * FROM kurakura_kl_erp.mailgroupdetails;
INSERT INTO kurakura_kl_test_erp.mailgroups SELECT * FROM kurakura_kl_erp.mailgroups;
INSERT INTO kurakura_kl_test_erp.manufacturers SELECT * FROM kurakura_kl_erp.manufacturers;
INSERT INTO kurakura_kl_test_erp.mrpcalendar SELECT * FROM kurakura_kl_erp.mrpcalendar;
INSERT INTO kurakura_kl_test_erp.mrpdemands SELECT * FROM kurakura_kl_erp.mrpdemands;
INSERT INTO kurakura_kl_test_erp.mrpdemandtypes SELECT * FROM kurakura_kl_erp.mrpdemandtypes;
INSERT INTO kurakura_kl_test_erp.mrpparameters SELECT * FROM kurakura_kl_erp.mrpparameters;
INSERT INTO kurakura_kl_test_erp.mrpplannedorders SELECT * FROM kurakura_kl_erp.mrpplannedorders;
INSERT INTO kurakura_kl_test_erp.mrprequirements SELECT * FROM kurakura_kl_erp.mrprequirements;
INSERT INTO kurakura_kl_test_erp.mrpsupplies SELECT * FROM kurakura_kl_erp.mrpsupplies;
INSERT INTO kurakura_kl_test_erp.offers SELECT * FROM kurakura_kl_erp.offers;
INSERT INTO kurakura_kl_test_erp.orderdeliverydifferenceslog SELECT * FROM kurakura_kl_erp.orderdeliverydifferenceslog;
INSERT INTO kurakura_kl_test_erp.packagingused SELECT * FROM kurakura_kl_erp.packagingused;
INSERT INTO kurakura_kl_test_erp.paymentmethods SELECT * FROM kurakura_kl_erp.paymentmethods;
INSERT INTO kurakura_kl_test_erp.paymentterms SELECT * FROM kurakura_kl_erp.paymentterms;
INSERT INTO kurakura_kl_test_erp.pcashdetails SELECT * FROM kurakura_kl_erp.pcashdetails;
INSERT INTO kurakura_kl_test_erp.pcexpenses SELECT * FROM kurakura_kl_erp.pcexpenses;
INSERT INTO kurakura_kl_test_erp.pctabexpenses SELECT * FROM kurakura_kl_erp.pctabexpenses;
INSERT INTO kurakura_kl_test_erp.pctabs SELECT * FROM kurakura_kl_erp.pctabs;
INSERT INTO kurakura_kl_test_erp.pctypetabs SELECT * FROM kurakura_kl_erp.pctypetabs;
INSERT INTO kurakura_kl_test_erp.periods SELECT * FROM kurakura_kl_erp.periods;
INSERT INTO kurakura_kl_test_erp.pickinglistdetails SELECT * FROM kurakura_kl_erp.pickinglistdetails;
INSERT INTO kurakura_kl_test_erp.pickinglists SELECT * FROM kurakura_kl_erp.pickinglists;
INSERT INTO kurakura_kl_test_erp.pricematrix SELECT * FROM kurakura_kl_erp.pricematrix;
INSERT INTO kurakura_kl_test_erp.prices SELECT * FROM kurakura_kl_erp.prices;
INSERT INTO kurakura_kl_test_erp.prodspecs SELECT * FROM kurakura_kl_erp.prodspecs;
INSERT INTO kurakura_kl_test_erp.purchdata SELECT * FROM kurakura_kl_erp.purchdata;
INSERT INTO kurakura_kl_test_erp.purchorderauth SELECT * FROM kurakura_kl_erp.purchorderauth;
INSERT INTO kurakura_kl_test_erp.purchorderdetails SELECT * FROM kurakura_kl_erp.purchorderdetails;
INSERT INTO kurakura_kl_test_erp.purchorders SELECT * FROM kurakura_kl_erp.purchorders;
INSERT INTO kurakura_kl_test_erp.qasamples SELECT * FROM kurakura_kl_erp.qasamples;
INSERT INTO kurakura_kl_test_erp.qatests SELECT * FROM kurakura_kl_erp.qatests;
INSERT INTO kurakura_kl_test_erp.recurringsalesorders SELECT * FROM kurakura_kl_erp.recurringsalesorders;
INSERT INTO kurakura_kl_test_erp.recurrsalesorderdetails SELECT * FROM kurakura_kl_erp.recurrsalesorderdetails;
INSERT INTO kurakura_kl_test_erp.relateditems SELECT * FROM kurakura_kl_erp.relateditems;
INSERT INTO kurakura_kl_test_erp.reportcolumns SELECT * FROM kurakura_kl_erp.reportcolumns;
INSERT INTO kurakura_kl_test_erp.reportfields SELECT * FROM kurakura_kl_erp.reportfields;
INSERT INTO kurakura_kl_test_erp.reportheaders SELECT * FROM kurakura_kl_erp.reportheaders;
INSERT INTO kurakura_kl_test_erp.reportlets SELECT * FROM kurakura_kl_erp.reportlets;
INSERT INTO kurakura_kl_test_erp.reportlinks SELECT * FROM kurakura_kl_erp.reportlinks;
INSERT INTO kurakura_kl_test_erp.reports SELECT * FROM kurakura_kl_erp.reports;
INSERT INTO kurakura_kl_test_erp.salesanalysis SELECT * FROM kurakura_kl_erp.salesanalysis;
INSERT INTO kurakura_kl_test_erp.salescat SELECT * FROM kurakura_kl_erp.salescat;
INSERT INTO kurakura_kl_test_erp.salescatprod SELECT * FROM kurakura_kl_erp.salescatprod;
INSERT INTO kurakura_kl_test_erp.salescattranslations SELECT * FROM kurakura_kl_erp.salescattranslations;
INSERT INTO kurakura_kl_test_erp.salesglpostings SELECT * FROM kurakura_kl_erp.salesglpostings;
INSERT INTO kurakura_kl_test_erp.salesman SELECT * FROM kurakura_kl_erp.salesman;
INSERT INTO kurakura_kl_test_erp.salesorderdetails SELECT * FROM kurakura_kl_erp.salesorderdetails;
INSERT INTO kurakura_kl_test_erp.salesorders SELECT * FROM kurakura_kl_erp.salesorders;
INSERT INTO kurakura_kl_test_erp.salestypes SELECT * FROM kurakura_kl_erp.salestypes;
INSERT INTO kurakura_kl_test_erp.sampleresults SELECT * FROM kurakura_kl_erp.sampleresults;
INSERT INTO kurakura_kl_test_erp.scripts SELECT * FROM kurakura_kl_erp.scripts;
INSERT INTO kurakura_kl_test_erp.securitygroups SELECT * FROM kurakura_kl_erp.securitygroups;
INSERT INTO kurakura_kl_test_erp.securityroles SELECT * FROM kurakura_kl_erp.securityroles;
INSERT INTO kurakura_kl_test_erp.securitytokens SELECT * FROM kurakura_kl_erp.securitytokens;
INSERT INTO kurakura_kl_test_erp.sellthroughsupport SELECT * FROM kurakura_kl_erp.sellthroughsupport;
INSERT INTO kurakura_kl_test_erp.shipmentcharges SELECT * FROM kurakura_kl_erp.shipmentcharges;
INSERT INTO kurakura_kl_test_erp.shipments SELECT * FROM kurakura_kl_erp.shipments;
INSERT INTO kurakura_kl_test_erp.shippers SELECT * FROM kurakura_kl_erp.shippers;
INSERT INTO kurakura_kl_test_erp.stockcategory SELECT * FROM kurakura_kl_erp.stockcategory;
INSERT INTO kurakura_kl_test_erp.stockcatproperties SELECT * FROM kurakura_kl_erp.stockcatproperties;
INSERT INTO kurakura_kl_test_erp.stockcheckfreeze SELECT * FROM kurakura_kl_erp.stockcheckfreeze;
INSERT INTO kurakura_kl_test_erp.stockcounts SELECT * FROM kurakura_kl_erp.stockcounts;
INSERT INTO kurakura_kl_test_erp.stockdescriptiontranslations SELECT * FROM kurakura_kl_erp.stockdescriptiontranslations;
INSERT INTO kurakura_kl_test_erp.stockitemproperties SELECT * FROM kurakura_kl_erp.stockitemproperties;
INSERT INTO kurakura_kl_test_erp.stockmaster SELECT * FROM kurakura_kl_erp.stockmaster;
INSERT INTO kurakura_kl_test_erp.stockmoves SELECT * FROM kurakura_kl_erp.stockmoves;
INSERT INTO kurakura_kl_test_erp.stockmovestaxes SELECT * FROM kurakura_kl_erp.stockmovestaxes;
INSERT INTO kurakura_kl_test_erp.stockrequest SELECT * FROM kurakura_kl_erp.stockrequest;
INSERT INTO kurakura_kl_test_erp.stockrequestitems SELECT * FROM kurakura_kl_erp.stockrequestitems;
INSERT INTO kurakura_kl_test_erp.stockserialitems SELECT * FROM kurakura_kl_erp.stockserialitems;
INSERT INTO kurakura_kl_test_erp.stockserialmoves SELECT * FROM kurakura_kl_erp.stockserialmoves;
INSERT INTO kurakura_kl_test_erp.suppallocs SELECT * FROM kurakura_kl_erp.suppallocs;
INSERT INTO kurakura_kl_test_erp.suppinvstogrn SELECT * FROM kurakura_kl_erp.suppinvstogrn;
INSERT INTO kurakura_kl_test_erp.suppliercontacts SELECT * FROM kurakura_kl_erp.suppliercontacts;
INSERT INTO kurakura_kl_test_erp.supplierdiscounts SELECT * FROM kurakura_kl_erp.supplierdiscounts;
INSERT INTO kurakura_kl_test_erp.suppliers SELECT * FROM kurakura_kl_erp.suppliers;
INSERT INTO kurakura_kl_test_erp.suppliertype SELECT * FROM kurakura_kl_erp.suppliertype;
INSERT INTO kurakura_kl_test_erp.supptrans SELECT * FROM kurakura_kl_erp.supptrans;
INSERT INTO kurakura_kl_test_erp.supptranstaxes SELECT * FROM kurakura_kl_erp.supptranstaxes;
INSERT INTO kurakura_kl_test_erp.systypes SELECT * FROM kurakura_kl_erp.systypes;
INSERT INTO kurakura_kl_test_erp.tags SELECT * FROM kurakura_kl_erp.tags;
INSERT INTO kurakura_kl_test_erp.taxauthorities SELECT * FROM kurakura_kl_erp.taxauthorities;
INSERT INTO kurakura_kl_test_erp.taxauthrates SELECT * FROM kurakura_kl_erp.taxauthrates;
INSERT INTO kurakura_kl_test_erp.taxcategories SELECT * FROM kurakura_kl_erp.taxcategories;
INSERT INTO kurakura_kl_test_erp.taxgroups SELECT * FROM kurakura_kl_erp.taxgroups;
INSERT INTO kurakura_kl_test_erp.taxgrouptaxes SELECT * FROM kurakura_kl_erp.taxgrouptaxes;
INSERT INTO kurakura_kl_test_erp.taxprovinces SELECT * FROM kurakura_kl_erp.taxprovinces;
INSERT INTO kurakura_kl_test_erp.tenderitems SELECT * FROM kurakura_kl_erp.tenderitems;
INSERT INTO kurakura_kl_test_erp.tenders SELECT * FROM kurakura_kl_erp.tenders;
INSERT INTO kurakura_kl_test_erp.tendersuppliers SELECT * FROM kurakura_kl_erp.tendersuppliers;
INSERT INTO kurakura_kl_test_erp.unitsofdimension SELECT * FROM kurakura_kl_erp.unitsofdimension;
INSERT INTO kurakura_kl_test_erp.unitsofmeasure SELECT * FROM kurakura_kl_erp.unitsofmeasure;
INSERT INTO kurakura_kl_test_erp.woitems SELECT * FROM kurakura_kl_erp.woitems;
INSERT INTO kurakura_kl_test_erp.worequirements SELECT * FROM kurakura_kl_erp.worequirements;
INSERT INTO kurakura_kl_test_erp.workcentres SELECT * FROM kurakura_kl_erp.workcentres;
INSERT INTO kurakura_kl_test_erp.workorders SELECT * FROM kurakura_kl_erp.workorders;
INSERT INTO kurakura_kl_test_erp.woserialnos SELECT * FROM kurakura_kl_erp.woserialnos;
INSERT INTO kurakura_kl_test_erp.www_users SELECT * FROM kurakura_kl_erp.www_users;
INSERT INTO kurakura_kl_test_erp.www_users_webshop SELECT * FROM kurakura_kl_erp.www_users_webshop;

UPDATE  `config` SET  `confvalue` =  'companies/kurakura_kl_test_erp/part_pics' WHERE  `confname` =  'part_pics_dir';
UPDATE  `config` SET  `confvalue` =  'companies/kurakura_kl_test_erp/reportwriter' WHERE  `confname` =  'reports_dir';
UPDATE  `config` SET  `confvalue` =  'companies/kurakura_kl_test_erp/logs' WHERE  `confname` =  'LogPath';

UPDATE  `config` SET  `confvalue` =  'TEST SHOP' WHERE  `confname` =  'ShopName';
UPDATE  `config` SET  `confvalue` =  'TEST SHOP' WHERE  `confname` =  'ShopTitle';

UPDATE  `config` SET  `confvalue` =  '' WHERE  `confname` =  'InventoryManagerEmail';
UPDATE  `config` SET  `confvalue` =  '' WHERE  `confname` =  'FactoryManagerEmail';
UPDATE  `config` SET  `confvalue` =  '' WHERE  `confname` =  'PurchasingManagerEmail';

UPDATE  `config` SET  `confvalue` =  'test' WHERE  `confname` =  'ShopMode';
UPDATE  `config` SET  `confvalue` =  '1372497542' WHERE  `confname` =  'ShopPayPalPassword';
UPDATE  `config` SET  `confvalue` =  'AKh80SD3d.pLz9oyaerqiR90yzDdARP3knOWMSTyjcbBNEns94xTl6WW' WHERE  `confname` =  'ShopPayPalSignature';
UPDATE  `config` SET  `confvalue` =  'testmerchant_api1.kapal-laut.com' WHERE  `confname` =  'ShopPayPalUser';

UPDATE www_users SET theme = "gel";
UPDATE www_users SET blocked = 0 WHERE userid LIKE "999%";

TRUNCATE audittrail;

SET FOREIGN_KEY_CHECKS=1;
