INSERT INTO `systypes` (`typeid`, `typename`, `typeno`) VALUES ('9000', 'KL Customer Invoice CC-PT', '1');
INSERT INTO `systypes` (`typeid`, `typename`, `typeno`) VALUES ('9001', 'KL Customer Invoice CASH-PT', '1');
INSERT INTO `systypes` (`typeid`, `typename`, `typeno`) VALUES ('9002', 'KL Customer Invoice CASH', '1');
INSERT INTO `scripts` (`script`, `pagesecurity`, `description`) VALUES ('KLRetailPOS.php', '1500', 'Modified version of CounterSales.php for KL allowing printing in Thermal printer');
INSERT INTO `scripts` (`script`, `pagesecurity`, `description`) VALUES ('KLRetailCustomerInfoCard.php', '1500', 'SPG input of customer info card');
INSERT INTO `scripts` (`script`, `pagesecurity`, `description`) VALUES ('PrintPOSReceipt.php', '1500', 'Print POS receipt');
ALTER TABLE `locations` ADD `klposcashaccount` VARCHAR(20) NULL COMMENT 'GL account for cash payments for KL POS ' AFTER `klyearlyrent`;
UPDATE `locations` SET `klposcashaccount` = '111111101' WHERE `locations`.`loccode` = 'TOK66';
UPDATE `locations` SET `klposcashaccount` = '111111102' WHERE `locations`.`loccode` = 'TOKSA';
UPDATE `locations` SET `klposcashaccount` = '111111103' WHERE `locations`.`loccode` = 'TOKKS';
UPDATE `locations` SET `klposcashaccount` = '111111107' WHERE `locations`.`loccode` = 'TOKMF';
UPDATE `locations` SET `klposcashaccount` = '111111108' WHERE `locations`.`loccode` = 'TOKUB';
UPDATE `locations` SET `klposcashaccount` = '111111109' WHERE `locations`.`loccode` = 'TOKSE';
UPDATE `locations` SET `klposcashaccount` = '111111110' WHERE `locations`.`loccode` = 'TOKPU';
UPDATE `locations` SET `klposcashaccount` = '111111111' WHERE `locations`.`loccode` = 'TOKSU';
UPDATE `locations` SET `klposcashaccount` = '111111112' WHERE `locations`.`loccode` = 'TOKOB';
UPDATE `locations` SET `klposcashaccount` = '111111113' WHERE `locations`.`loccode` = 'TOKSS';
UPDATE `locations` SET `klposcashaccount` = '111111114' WHERE `locations`.`loccode` = 'TOKPA';
UPDATE `locations` SET `klposcashaccount` = '111111115' WHERE `locations`.`loccode` = 'TOKKA';
UPDATE `locations` SET `klposcashaccount` = '111111116' WHERE `locations`.`loccode` = 'TOKMU';
UPDATE `locations` SET `klposcashaccount` = '111111117' WHERE `locations`.`loccode` = 'TOKPS';
UPDATE `locations` SET `klposcashaccount` = '111111118' WHERE `locations`.`loccode` = 'TOKAR';
UPDATE `locations` SET `klposcashaccount` = '111111119' WHERE `locations`.`loccode` = 'TOKSB';
UPDATE `locations` SET `klposcashaccount` = '111111120' WHERE `locations`.`loccode` = 'TOKPB';
UPDATE `locations` SET `klposcashaccount` = '111111121' WHERE `locations`.`loccode` = 'TOKBU';
UPDATE `locations` SET `klposcashaccount` = '111111122' WHERE `locations`.`loccode` = 'TOKM2';