<?php

if (!isset($PathPrefix)) {
	header('Location: ../');
	exit();
}

if (!function_exists('__')) {
	// NB: this function always exists if this page is included after api_session.php, and that is guaranteed by the above check.
	// However, we still get a fatal error if this page is accessed directly, because in that case php tries to
	// parse the code below even without executing it. So we resort to this silly hack
	function __($string) {return $string;}
}

/* Define error codes that are returned by api functions */
define('NoAuthorisation', 1);
define('IncorrectDebtorNumberLength', 1000);
define('DebtorNoAlreadyExists', 1001);
define('IncorrectDebtorNameLength', 1002);
define('InvalidAddressLine', 1003);
define('CurrencyCodeNotSetup', 1004);
define('SalesTypeNotSetup', 1005);
define('InvalidClientSinceDate', 1006);
define('HoldReasonNotSetup', 1007);
define('PaymentTermsNotSetup', 1008);
define('InvalidDiscount', 1009);
define('InvalidPaymentDiscount', 1010);
define('InvalidLastPaid', 1011);
define('InvalidLastPaidDate', 1012);
define('InvalidCreditLimit', 1013);
define('InvalidInvAddrBranch', 1014);
define('InvalidDiscountCode', 1015);
define('InvalidEDIInvoices', 1016);
define('InvalidEDIOrders', 1017);
define('InvalidEDIReference', 1018);
define('InvalidEDITransport', 1019);
define('InvalidEDIAddress', 1020);
define('InvalidEDIServerUser', 1021);
define('InvalidEDIServerPassword', 1022);
define('InvalidTaxRef', 1023);
define('InvalidCustomerPOLine', 1024);
define('DatabaseUpdateFailed', 1025);
define('NoDebtorNumber', 1026);
define('DebtorDoesntExist', 1027);
define('IncorrectBranchNumberLength', 1028);
define('BranchNoAlreadyExists', 1029);
define('IncorrectBranchNameLength', 1030);
define('InvalidEstDeliveryDays', 1031);
define('AreaCodeNotSetup', 1032);
define('SalesmanCodeNotSetup', 1033);
define('InvalidFwdDate', 1034);
define('InvalidPhoneNumber', 1035);
define('InvalidFaxNumber', 1036);
define('InvalidContactName', 1037);
define('InvalidEmailAddress', 1038);
define('LocationCodeNotSetup', 1039);
define('TaxGroupIdNotSetup', 1040);
define('ShipperNotSetup', 1041);
define('InvalidDeliverBlind', 1042);
define('InvalidDisableTrans', 1043);
define('InvalidSpecialInstructions', 1044);
define('InvalidCustBranchCode', 1045);
define('BranchNoDoesntExist', 1046);
define('StockCodeDoesntExist', 1047);
define('StockCategoryDoesntExist', 1048);
define('IncorrectStockDescriptionLength', 1049);
define('IncorrectUnitsLength', 1050);
define('IncorrectMBFlag', 1051);
define('InvalidCurCostDate', 1052);
define('InvalidActualCost', 1053);
define('InvalidLowestLevel', 1054);
define('InvalidDiscontinued', 1055);
define('InvalidEOQ', 1056);
define('InvalidVolume', 1057);
define('InvalidKgs', 1058);
define('IncorrectBarCodeLength', 1059);
define('IncorrectDiscountCategory', 1060);
define('TaxCategoriesDoesntExist', 1061);
define('InvalidSerialised', 1062);
define('InvalidPerishable', 1064);
define('InvalidDecmalPlaces', 1065);
define('IncorrectLongStockDescriptionLength', 1066);
define('StockCodeAlreadyExists', 1067);
define('TransactionNumberAlreadyExists', 1068);
define('InvalidTranDate', 1069);
define('InvalidSettled', 1070);
define('IncorrectReference', 1071);
define('IncorrectTpe', 1072);
define('InvalidOrderNumbers', 1073);
define('InvalidExchangeRate', 1074);
define('InvalidOVAmount', 1075);
define('InvalidOVGst', 1076);
define('InvalidOVFreight', 1077);
define('InvalidDiffOnExchange', 1078);
define('InvalidAllocation', 1079);
define('IncorrectInvoiceText', 1080);
define('InvalidShipVia', 1081);
define('InvalidEdiSent', 1082);
define('InvalidConsignment', 1083);
define('InvalidLastCost', 1084);
define('InvalidMaterialCost', 1085);
define('InvalidLabourCost', 1086);
define('InvalidOverheadCost', 1087);
define('InvalidCustomerRef', 1088);
define('InvalidBuyerName', 1089);
define('InvalidComments', 1090);
define('InvalidOrderDate', 1091);
define('InvalidDeliverTo', 1092);
define('InvalidFreightCost', 1094);
define('InvalidDeliveryDate', 1095);
define('InvalidQuotationFlag', 1096);
define('OrderHeaderNotSetup', 1097);
define('InvalidUnitPrice', 1098);
define('InvalidQuantity', 1099);
define('InvalidDiscountPercent', 1100);
define('InvalidNarrative', 1101);
define('InvalidItemDueDate', 1102);
define('InvalidPOLine', 1103);
define('GLAccountCodeAlreadyExists', 1104);
define('IncorrectAccountNameLength', 1105);
define('AccountGroupDoesntExist', 1106);
define('GLAccountSectionAlreadyExists', 1107);
define('IncorrectSectionNameLength', 1108);
define('GLAccountGroupAlreadyExists', 1109);
define('GLAccountSectionDoesntExist', 1110);
define('InvalidPandL', 1111);
define('InvalidSequenceInTB', 1112);
define('GLAccountGroupDoesntExist', 1113);
define('InvalidLatitude', 1114);
define('InvalidLongitude', 1115);
define('CustomerTypeNotSetup', 1116);
define('NoPricesSetup', 1117);
define('InvalidInvoicedQuantity', 1118);
define('InvalidActualDispatchDate', 1119);
define('InvalidCompletedFlag', 1120);
define('InvalidCategoryID', 1121);
define('InvalidCategoryDescription', 1122);
define('InvalidStockType', 1123);
define('GLAccountCodeDoesntExists', 1124);
define('StockCategoryAlreadyExists', 1125);
define('SupplierNoAlreadyExists', 1126);
define('IncorrectSupplierNameLength', 1127);
define('InvalidSupplierSinceDate', 1128);
define('InvalidBankAccount', 1129);
define('InvalidBankReference', 1130);
define('InvalidBankPartics', 1131);
define('InvalidRemittanceFlag', 1132);
define('FactorCompanyNotSetup', 1133);
define('SupplierNoDoesntExists', 1134);
define('InvalidSuppliersUOM', 1135);
define('InvalidConversionFactor', 1136);
define('InvalidSupplierDescription', 1137);
define('InvalidLeadTime', 1138);
define('InvalidPreferredFlag', 1139);
define('StockSupplierLineDoesntExist', 1140);
define('InvalidRequiredByDate', 1141);
define('InvalidStartDate', 1142);
define('InvalidCostIssued', 1143);
define('InvalidQuantityRequired', 1144);
define('InvalidQuantityReceived', 1145);
define('InvalidStandardCost', 1146);
define('IncorrectSerialNumber', 1147);
define('WorkOrderDoesntExist', 1148);
define('InvalidIssuedQuantity', 1149);
define('InvalidTransactionDate', 1150);
define('InvalidReceivedQuantity', 1151);
define('ItemNotControlled', 1152);
define('ItemSerialised', 1153);
define('BatchNumberDoesntExist', 1154);
define('BatchIsEmpty', 1155);
define('NoSuchArea', 1156);
define('NoSuchSalesMan', 1157);
define('NoCompanyRecord',1158);
define('NoReadOrder',1159);
define('NoReadOrderLines',1160);
define('NoTaxProvince',1161);
define('TaxRatesFailed',1162);
define('NoReadCustomerBranch',1163);
define('NoReadItem',1164);
define('MustBeReceiptOrCreditNote',1165);
define('NoTransactionToAllocate',1166);
define('InvalidOVDiscount',1167);
define('IncorrectLocationCodeLength',1168);
define('LocationCodeAlreadyExists',1169);
define('LocationCodeDoesntExist',1170);
define('IncorrectLocationNameLength',1171);
define('TaxProvinceIdNotSetup',1172);
define('InvalidControlled',1173);


/* Array of Descriptions of errors */
$ErrorDescription['1'] = __('No Authorisation');
$ErrorDescription['1000'] = __('Incorrect Debtor Number Length');
$ErrorDescription['1001'] = __('Debtor No Already Exists');
$ErrorDescription['1002'] = __('Incorrect Debtor Name Length');
$ErrorDescription['1003'] = __('Invalid Address Line');
$ErrorDescription['1004'] = __('Currency Code Not Setup');
$ErrorDescription['1005'] = __('Sales Type Not Setup');
$ErrorDescription['1006'] = __('Invalid Client Since Date');
$ErrorDescription['1007'] = __('Hold Reason Not Setup');
$ErrorDescription['1008'] = __('Payment Terms Not Setup');
$ErrorDescription['1009'] = __('Invalid Discount');
$ErrorDescription['1010'] = __('Invalid Payment Discount');
$ErrorDescription['1011'] = __('Invalid Last Paid');
$ErrorDescription['1012'] = __('Invalid Last Paid Date');
$ErrorDescription['1013'] = __('Invalid Credit Limit');
$ErrorDescription['1014'] = __('Invalid Inv Address Branch');
$ErrorDescription['1015'] = __('Invalid Discount Code');
$ErrorDescription['1016'] = __('Invalid EDI Invoices');
$ErrorDescription['1017'] = __('Invalid EDI Orders');
$ErrorDescription['1018'] = __('Invalid EDI Reference');
$ErrorDescription['1019'] = __('Invalid EDI Transport');
$ErrorDescription['1020'] = __('Invalid EDI Address');
$ErrorDescription['1021'] = __('Invalid EDI Server User');
$ErrorDescription['1022'] = __('Invalid EDI Server Password');
$ErrorDescription['1023'] = __('Invalid Tax Reference');
$ErrorDescription['1024'] = __('Invalid CustomerPOLine');
$ErrorDescription['1025'] = __('Database Update Failed');
$ErrorDescription['1026'] = __('No Debtor Number');
$ErrorDescription['1027'] = __('Debtor Does not Exist');
$ErrorDescription['1028'] = __('Incorrect Branch Number Length');
$ErrorDescription['1029'] = __('Branch No Already Exists');
$ErrorDescription['1030'] = __('Incorrect Branch Name Length');
$ErrorDescription['1031'] = __('Invalid Est Delivery Days');
$ErrorDescription['1032'] = __('Area Code Not Setup');
$ErrorDescription['1033'] = __('Salesman Code Not Setup');
$ErrorDescription['1034'] = __('Invalid Fwd Date');
$ErrorDescription['1035'] = __('Invalid Phone Number');
$ErrorDescription['1036'] = __('Invalid Fax Number');
$ErrorDescription['1037'] = __('Invalid Contact Name');
$ErrorDescription['1038'] = __('Invalid Email Address');
$ErrorDescription['1039'] = __('Location Code Not Setup');
$ErrorDescription['1040'] = __('Tax Group Id Not Setup');
$ErrorDescription['1041'] = __('Shipper Not Setup');
$ErrorDescription['1042'] = __('Invalid Deliver Blind');
$ErrorDescription['1043'] = __('Invalid Disable Transactions');
$ErrorDescription['1044'] = __('Invalid Special Instructions');
$ErrorDescription['1045'] = __('Invalid Customer Branch Code');
$ErrorDescription['1046'] = __('Branch No Does not Exist');
$ErrorDescription['1047'] = __('Stock Code Does not Exist');
$ErrorDescription['1048'] = __('Stock Category Does not Exist');
$ErrorDescription['1049'] = __('Incorrect Stock Description Length');
$ErrorDescription['1050'] = __('Incorrect Units Length');
$ErrorDescription['1051'] = __('Incorrect MB Flag');
$ErrorDescription['1052'] = __('Invalid Current Cost Date');
$ErrorDescription['1053'] = __('Invalid Actual Cost');
$ErrorDescription['1054'] = __('Invalid Lowest Level');
$ErrorDescription['1055'] = __('Invalid Discontinued');
$ErrorDescription['1056'] = __('Invalid EOQ');
$ErrorDescription['1057'] = __('Invalid Volume');
$ErrorDescription['1058'] = __('Invalid Kgs');
$ErrorDescription['1059'] = __('Incorrect BarCode Length');
$ErrorDescription['1060'] = __('Incorrect Discount Category');
$ErrorDescription['1061'] = __('Tax Category Does not Exist');
$ErrorDescription['1062'] = __('Invalid Serialised');
$ErrorDescription['1063'] = __('Incorrect Append File');
$ErrorDescription['1064'] = __('Invalid Perishable');
$ErrorDescription['1065'] = __('Invalid Decimal Places');
$ErrorDescription['1066'] = __('Incorrect Long Stock Description Length');
$ErrorDescription['1067'] = __('Stock Code Already Exists');
$ErrorDescription['1068'] = __('Transaction Number Already Exists');
$ErrorDescription['1069'] = __('Invalid Transaction Date');
$ErrorDescription['1070'] = __('Invalid Settled');
$ErrorDescription['1071'] = __('Incorrect Reference');
$ErrorDescription['1072'] = __('Incorrect TPE');
$ErrorDescription['1073'] = __('Invalid Order Numbers');
$ErrorDescription['1074'] = __('Invalid Exchange Rate');
$ErrorDescription['1075'] = __('Invalid OV Amount');
$ErrorDescription['1076'] = __('Invalid OV Gst');
$ErrorDescription['1077'] = __('Invalid OV Freight');
$ErrorDescription['1078'] = __('Invalid Diff On Exchange');
$ErrorDescription['1079'] = __('Invalid Allocation');
$ErrorDescription['1080'] = __('Incorrect Invoice Text');
$ErrorDescription['1081'] = __('Invalid Ship Via');
$ErrorDescription['1082'] = __('Invalid Edi Sent');
$ErrorDescription['1083'] = __('Invalid Consignment');
$ErrorDescription['1084'] = __('Invalid Last Cost');
$ErrorDescription['1085'] = __('Invalid Material Cost');
$ErrorDescription['1086'] = __('Invalid Labour Cost');
$ErrorDescription['1087'] = __('Invalid Overhead Cost');
$ErrorDescription['1088'] = __('Invalid Customer Reference');
$ErrorDescription['1089'] = __('Invalid Buyer Name');
$ErrorDescription['1090'] = __('Invalid Comments');
$ErrorDescription['1091'] = __('Invalid Order Date');
$ErrorDescription['1092'] = __('Invalid Delivery Name');
$ErrorDescription['1094'] = __('Invalid Freight Cost');
$ErrorDescription['1095'] = __('Invalid Delivery Date');
$ErrorDescription['1096'] = __('Invalid Quotation Flag');
$ErrorDescription['1097'] = __('Order header not setup');
$ErrorDescription['1098'] = __('Invalid unit cost');
$ErrorDescription['1099'] = __('Invalid Quantity');
$ErrorDescription['1100'] = __('Invalid Discount Percent');
$ErrorDescription['1101'] = __('Invalid Narrative');
$ErrorDescription['1102'] = __('Invalid Item Due');
$ErrorDescription['1103'] = __('Invalid PO line');
$ErrorDescription['1104'] = __('GL account code already exists');
$ErrorDescription['1105'] = __('GL account code name is incorrect length');
$ErrorDescription['1106'] = __('GL account group does not exist');
$ErrorDescription['1107'] = __('GL account section already exists');
$ErrorDescription['1108'] = __('GL account section name is incorrect length');
$ErrorDescription['1109'] = __('GL account group already exists');
$ErrorDescription['1110'] = __('GL account section does not exist');
$ErrorDescription['1111'] = __('Invalid profit and loss flag');
$ErrorDescription['1112'] = __('Invalid sequenceintb figure');
$ErrorDescription['1113'] = __('GL account group does not exist');
$ErrorDescription['1114'] = __('Invalid Latitude figure');
$ErrorDescription['1115'] = __('Invalid Longitude figure');
$ErrorDescription['1116'] = __('Customer type not set up');
$ErrorDescription['1117'] = __('No sales prices setup');
$ErrorDescription['1118'] = __('Invalid invoiced quantity');
$ErrorDescription['1119'] = __('Invalid actual dispatch date');
$ErrorDescription['1120'] = __('Invalid completed flag');
$ErrorDescription['1121'] = __('Invalid category id');
$ErrorDescription['1122'] = __('Invalid category description');
$ErrorDescription['1123'] = __('Invalid stock type');
$ErrorDescription['1124'] = __('GL account code does not exist');
$ErrorDescription['1125'] = __('Stock category already exists');
$ErrorDescription['1126'] = __('Supplier code already exists');
$ErrorDescription['1127'] = __('Incorrect supplier name length, or supplier name does not exist');
$ErrorDescription['1128'] = __('Incorrect supplier since date');
$ErrorDescription['1129'] = __('Incorrect bank account');
$ErrorDescription['1130'] = __('Incorrect bank reference');
$ErrorDescription['1131'] = __('Incorrect bank partics');
$ErrorDescription['1132'] = __('Incorrect remittance flags');
$ErrorDescription['1133'] = __('Factor company not set up');
$ErrorDescription['1134'] = __('Supplier does not exist');
$ErrorDescription['1135'] = __('Incorrect suppliers UOM');
$ErrorDescription['1136'] = __('Incorrect conversion factor');
$ErrorDescription['1137'] = __('Incorrect supplier description');
$ErrorDescription['1138'] = __('Invalid Lead time');
$ErrorDescription['1139'] = __('Invalid Preferred flag');
$ErrorDescription['1140'] = __('StockID SupplierID line does not exist');
$ErrorDescription['1141'] = __('Invalid Required By Date');
$ErrorDescription['1142'] = __('Invalid Start Date');
$ErrorDescription['1143'] = __('Invalid Cost Issued');
$ErrorDescription['1144'] = __('Invalid Quantity Required');
$ErrorDescription['1145'] = __('Invalid Quantity Received');
$ErrorDescription['1146'] = __('Invalid Standard Cost');
$ErrorDescription['1147'] = __('Invalid Serial Number or Lot Reference');
$ErrorDescription['1148'] = __('Work order number does not exist');
$ErrorDescription['1149'] = __('Invalid issued quantity');
$ErrorDescription['1150'] = __('Invalid transaction date');
$ErrorDescription['1151'] = __('Invalid received quantity');
$ErrorDescription['1152'] = __('Stock item is not controlled');
$ErrorDescription['1153'] = __('Stock item is serialised');
$ErrorDescription['1154'] = __('Batch number does not exist');
$ErrorDescription['1155'] = __('Batch is empty');
$ErrorDescription['1156'] = __('No such area');
$ErrorDescription['1157'] = __('No such salesman');
$ErrorDescription['1158'] = __('Unable to read company record');
$ErrorDescription['1159'] = __('Unable to read sales order');
$ErrorDescription['1160'] = __('Unable to read sales order lines');
$ErrorDescription['1161'] = __('Unable to get tax province of location');
$ErrorDescription['1162'] = __('Unable to read tax rates for this item and tax group');
$ErrorDescription['1163'] = __('Unable to read customer and branch details');
$ErrorDescription['1164'] = __('Unable to read credit note item details');
$ErrorDescription['1165'] = __('Can only allocate receipts or a credit notes');
$ErrorDescription['1166'] = __('No transaction found to allocate');
$ErrorDescription['1167'] = __('Invalid OV Discount');
$ErrorDescription['1168'] = __('Incorrect Location Code Length');
$ErrorDescription['1169'] = __('Location Code Already Exists');
$ErrorDescription['1170'] = __('Location Code Does not Exist');
$ErrorDescription['1171'] = __('Incorrect Location Name Length');
$ErrorDescription['1172'] = __('Tax Province ID Not Setup');
$ErrorDescription['1173'] = __('Invalid Controlled');
